name: LeetCode Stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate LeetCode stats image
        uses: zwacky/leetcode-stats-card@v1.4.3
        with:
          username: "jia-shui-bu-fang-tang"
          leetcode_cn: true
          output: leetcode_stats.svg
          theme: dark
          locale: en

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}